package com.facebook.react.uimanager;

import android.view.View;

/**
 * Compatibility shim for libraries generated by react-native-codegen.
 * This interface exists in newer React Native versions.
 */
public interface ViewManagerWithGeneratedInterface<T extends View> {}
